version: '3'
services:
  rabbitmq:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 4369:4369
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432